--
-- Visando reiniciar o modelo relacional a partir dessa aula, vamos recriar o projeto Sakspildap
-- Entre dentro do diretório Sakspildap_v2 e execute os scritps abaixo
--
@<diretorio_aluno>\apaga.sql
@<diretorio_aluno>\cria.sql
 

--
-- Slide 17
--
ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy hh24:mi:ss';

--
-- Slide 20
--
INSERT INTO T_SIP_DEPTO (CD_DEPTO, NM_DEPTO, SG_DEPTO) 
VALUES (1, 'FINANCEIRO', 'FIN');

COMMIT;

--
-- Slide 21
--
INSERT INTO T_SIP_DEPTO VALUES (2, 'MARKETING', 'MKT');

COMMIT;

--
-- Slide 22
--
SELECT * FROM T_SIP_DEPTO;


--
-- Slide 23
--
INSERT INTO T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
VALUES (1,'Projeto HandsFree Sakspidap', TO_DATE('19/09/2020','DD/MM/YYYY'), TO_DATE('18/05/2021','DD/MM/YYYY'));
COMMIT;


--
-- Slide 24
--
INSERT INTO T_SIP_FUNCIONARIO (NR_MATRICULA, CD_DEPTO, NM_FUNCIONARIO, DT_NASCIMENTO, VL_SALARIO, DT_ADMISSAO)
VALUES (12345, 1, 'Maria Linda da Silva', TO_DATE('21/03/1998','DD/MM/YYYY'), 13559.87,  TO_DATE('18/05/2008','DD/MM/YYYY'));
COMMIT;

--
-- Slide 25
--
SELECT * FROM T_SIP_FUNCIONARIO;


--
-- Slide 26
--
INSERT INTO T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO)
VALUES (2,'Projeto Industria 4.0 SKW', TO_DATE('22/01/2020','DD/MM/YYYY'));

INSERT INTO T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
VALUES (3,'Projeto App Impressora 3D TDI', TO_DATE('25/08/2020','DD/MM/YYYY'), NULL);
COMMIT;

--
-- Slide 27
--
SELECT * FROM T_SIP_PROJETO;

--
-- Slide 28
--
CREATE TABLE t_sip_projeto_bkp (
    cd_projeto         NUMBER(10) NOT NULL,
    nm_projeto         VARCHAR2(40) NOT NULL,
    dt_inicio          DATE NOT NULL,
    dt_termino         DATE
);

ALTER TABLE t_sip_projeto_bkp ADD CONSTRAINT pk_sak_proj_bkp PRIMARY KEY ( cd_projeto );

--
-- Slide 29
--
INSERT INTO T_SIP_PROJETO_BKP 
( SELECT CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO
  FROM T_SIP_PROJETO WHERE DT_TERMINO IS NOT NULL
);
COMMIT;


--
-- Slide 31
--
UPDATE T_SIP_FUNCIONARIO 
SET NM_FUNCIONARIO = 'Maria Linda Ragnarok',     
	DT_NASCIMENTO = TO_DATE ('21/03/1998','DD/MM/YYYY')
WHERE NR_MATRICULA = 12345;

--
-- Slide 32
--
UPDATE T_SIP_FUNCIONARIO 
SET VL_SALARIO = VL_SALARIO * 1.05;


--
-- Slide 33
-- Atualiza todas as linhas da tabela T_SIP_PROJETO
--
UPDATE T_SIP_PROJETO
SET DT_TERMINO =
( SELECT DT_TERMINO
  FROM T_SIP_PROJETO_BKP
  WHERE CD_PROJETO = 1
);

--
-- Slide 34
--

SELECT * FROM T_SIP_PROJETO;

SELECT * FROM T_SIP_PROJETO_BKP;

--
-- Slide 37
--
DELETE FROM T_SIP_FUNCIONARIO
WHERE CD_DEPTO = 1 AND 
DT_ADMISSAO > TO_DATE('01/01/2000', 'DD/MM/YYYY');

SELECT * FROM T_SIP_FUNCIONARIO;


--
-- Slide 38
--
DELETE FROM T_SIP_PROJETO
WHERE CD_PROJETO = 
(SELECT CD_PROJETO 
 FROM T_SIP_PROJETO_BKP
 WHERE CD_PROJETO = 1
 );

--
-- Slide 39
--
SELECT * FROM T_SIP_PROJETO;

SELECT * FROM T_SIP_PROJETO_BKP;

--
-- Slide 45
--
DELETE FROM T_SIP_PROJETO;
select * from T_SIP_PROJETO;
ROLLBACK;


--
-- Slide 47
--
INSERT INTO T_SIP_DEPTO (CD_DEPTO, NM_DEPTO, SG_DEPTO) 
VALUES (1, 'DIRETORIA', 'TOP');


--
-- Slide 48
--
INSERT INTO T_SIP_DEPTO (CD_DEPTO, NM_DEPTO, SG_DEPTO) 
VALUES (6, 'MARKETING', 'MAR');

--
-- Slide 49
--
INSERT INTO T_SIP_FUNCIONARIO (NR_MATRICULA, CD_DEPTO, NM_FUNCIONARIO, DT_NASCIMENTO, VL_SALARIO, DT_ADMISSAO)
VALUES (12346, 7, 'GugBlaus Stroubs', TO_DATE('21/03/1998','DD/MM/YYYY'), 13559.87,  TO_DATE('18/05/2008','DD/MM/YYYY'));


--
-- Slide 50
--
INSERT INTO T_SIP_FUNCIONARIO VALUES
(12349, 1, 'TESTE', TO_DATE('01/01/1900','DD/MM/YYYY'), TO_DATE('01/01/1900','DD/MM/YYYY'),600);


--
-- Slide 51
--
INSERT INTO T_SIP_DEPTO (CD_DEPTO, NM_DEPTO, SG_DEPTO) 
VALUES (78773, 'TECNOLOGIAS AVANÇADAS', 'TAV');

DESC T_SIP_DEPTO;
--
-- Slide 52
--
INSERT INTO T_SIP_DEPTO (CD_DEPTO, NM_DEPTO, SG_DEPTO) 
VALUES ('XX', 'TECNOLOGIAS AVANÇADAS', 'TAV');

--
-- Slide 53
--
INSERT INTO T_SIP_DEPTO (CD_DEPTO, NM_DEPTO, SG_DEPTO) 
VALUES (15, 'TECNOLOGIAS AVANÇADAS');
 
--
-- Slide 53
--
INSERT INTO T_SIP_DEPTO (CD_DEPTO, NM_DEPTO, SG_DEPTO) 
VALUES (15, 'TECNOLOGIAS AVANÇADAS','TAV', 'ATIVO');
 
 
 --
-- Slide 54
--
INSERT INTO T_SIP_DEPTO VALUES (5, 'DEPTO TESTE','TST', 'ATIVO','XXX');

 


