-- Slide 10
SELECT * FROM T_SAK_FUNCIONARIO;

-- Slide 11
SELECT T_SAK_FUNCIONARIO.CD_FUNC, T_SAK_FUNCIONARIO.NM_FUNCIONARIO, T_SAK_FUNCIONARIO.DT_NASCIMENTO, T_SAK_FUNCIONARIO.CD_DEPTO
FROM T_SAK_FUNCIONARIO;

SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO, F.CD_DEPTO
FROM T_SAK_FUNCIONARIO F ;

-- Slide 12
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO, F.CD_DEPTO
FROM T_SAK_FUNCIONARIO F
WHERE F.CD_DEPTO = 6;

-- Slide 13
SELECT DISTINCT F.CD_DEPTO
FROM T_SAK_FUNCIONARIO F;

-- Slide 15
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO, F.VL_SALARIO * 1.05
FROM T_SAK_FUNCIONARIO F;

-- Slide 16
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO, (F.VL_SALARIO * 12) + 1000  VL_SALARIO_ANUAL
FROM T_SAK_FUNCIONARIO F;

-- Slide 18
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO, F.VL_SALARIO * 1.05 "VALOR AJUSTADO"
FROM T_SAK_FUNCIONARIO F;

-- Slide 20
SELECT D.CD_DEPTO, D.NM_DEPTO
FROM T_SAK_DEPTO D
ORDER BY D.NM_DEPTO;

-- Slide 20
SELECT D.CD_DEPTO, D.NM_DEPTO
FROM T_SAK_DEPTO D
ORDER BY D.NM_DEPTO DESC;

-- Slide 22
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO, F.CD_DEPTO
FROM T_SAK_FUNCIONARIO F
WHERE  F.CD_DEPTO > 1 
ORDER BY  4 ASC, 2 DESC;

-- Slide 23
SELECT F.CD_FUNC Matricula, 
       F.NM_FUNCIONARIO Nome_Funcionario, 
	   F.VL_SALARIO "Salário Bruto", 
	   F.CD_DEPTO Codigo_Departamento
FROM T_SAK_FUNCIONARIO F
ORDER BY "Salário Bruto" DESC;

-- Slide 30
SELECT F.CD_FUNC Matricula, 
       F.NM_FUNCIONARIO Nome_Funcionario, 
	   F.VL_SALARIO "Salário Bruto", 
	   F.CD_DEPTO Codigo_Departamento
FROM T_SAK_FUNCIONARIO F
WHERE F.VL_SALARIO > 2999.99;

-- Slide 31
SELECT F.CD_FUNC Matricula, 
       F.NM_FUNCIONARIO Nome_Funcionario, 
	   F.VL_SALARIO "Salário Bruto", 
	   F.CD_DEPTO Codigo_Departamento
FROM T_SAK_FUNCIONARIO F
WHERE F.NM_FUNCIONARIO = 'Solange Amoedo Frois';

-- Slide 32
SELECT 	*
FROM 	T_SAK_FUNCIONARIO F
WHERE 	F.DT_ADMISSAO >= TO_DATE('01/01/2018','DD/MM/YYYY');

-- Slide 34
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.CD_DEPTO, F.DT_ADMISSAO
FROM   T_SAK_FUNCIONARIO F
WHERE  F.DT_ADMISSAO >= TO_DATE('01/01/2012','DD/MM/YYYY')
AND F.CD_DEPTO > 3;

-- Slide 35
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.CD_DEPTO, F.DT_ADMISSAO
FROM   T_SAK_FUNCIONARIO F
WHERE  F.DT_ADMISSAO >= TO_DATE('01/01/2018','DD/MM/YYYY')
OR F.CD_DEPTO = 7;


-- Slide 36
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.CD_DEPTO, F.DT_ADMISSAO, F.VL_SALARIO
FROM   T_SAK_FUNCIONARIO F
WHERE  NOT F.CD_DEPTO = 10;


-- Slide 38 e 39
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.CD_DEPTO, F.DT_ADMISSAO, F.VL_SALARIO
FROM   T_SAK_FUNCIONARIO F
WHERE  F.DT_ADMISSAO BETWEEN TO_DATE('01/01/2021','DD/MM/YYYY') 
AND TO_DATE('31/12/2021','DD/MM/YYYY');

SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.CD_DEPTO, F.DT_ADMISSAO, F.VL_SALARIO
FROM   T_SAK_FUNCIONARIO F
WHERE  F.VL_SALARIO BETWEEN 5000 AND 10000;

-- Slide 40
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.CD_DEPTO, F.DT_ADMISSAO, F.VL_SALARIO
FROM   T_SAK_FUNCIONARIO F
WHERE  F.CD_DEPTO IN (1,7,4);

-- Slide 41
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.CD_DEPTO, F.DT_ADMISSAO, F.VL_SALARIO
FROM   T_SAK_FUNCIONARIO F
WHERE  F.CD_DEPTO NOT IN (1,7,4);

-- Slide 42
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.CD_DEPTO, F.DT_ADMISSAO, F.VL_SALARIO
FROM   T_SAK_FUNCIONARIO F
WHERE  TO_CHAR(F.DT_ADMISSAO,'YYYY') IN ('2015', '2018', '2021');

-- Slide 43
SELECT P.CD_PROJETO, P.NM_PROJETO, P.DT_INICIO, P.DT_TERMINO
FROM T_SAK_PROJETO P
WHERE P.DT_TERMINO IS NOT NULL;

-- Slide 44
SELECT P.CD_PROJETO, P.NM_PROJETO, P.DT_INICIO, P.DT_TERMINO
FROM T_SAK_PROJETO P
WHERE P.DT_TERMINO IS NULL;

-- Slide 46
SELECT D.CD_DEPTO, D.NM_DEPTO
FROM T_SAK_DEPTO D
WHERE D.NM_DEPTO LIKE 'CO%';

-- Slide 47
SELECT D.CD_DEPTO, D.NM_DEPTO
FROM T_SAK_DEPTO D
WHERE D.NM_DEPTO LIKE '_E%';

-- Slide 48
SELECT D.CD_DEPTO, D.NM_DEPTO
FROM T_SAK_DEPTO D
WHERE D.NM_DEPTO LIKE '___UR%';

-- Slide 49
SELECT D.CD_DEPTO, D.NM_DEPTO
FROM T_SAK_DEPTO D
WHERE D.NM_DEPTO LIKE '%ME%';

-- Slide 51
SELECT 'O funcionário ' ||  F.NM_FUNCIONARIO || ' de código ' ||
TO_CHAR(F.CD_FUNC) || ', foi admitido em ' || TO_CHAR(F.DT_ADMISSAO, 'DD/MM/YYYY') 
|| ' e recebe o salário de R$ ' || TO_CHAR(F.VL_SALARIO)
FROM T_SAK_FUNCIONARIO F;

-- Slide 53
SELECT ROWNUM, D.CD_DEPTO, D.NM_DEPTO
FROM T_SAK_DEPTO D;

-- Slide 54
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.CD_DEPTO, F.DT_ADMISSAO, F.VL_SALARIO,
F.VL_SALARIO * 12 SALARIO_ANUAL
FROM   T_SAK_FUNCIONARIO F
WHERE  ROWNUM < 4;


-- Slide 57
SELECT ROWNUM AS RANK,
       X.NM_FUNCIONARIO,
       X.VL_SALARIO 
FROM
(
SELECT F.NM_FUNCIONARIO, F.VL_SALARIO
FROM   T_SAK_FUNCIONARIO F
ORDER BY VL_SALARIO DESC
) X
WHERE  ROWNUM < 4;

-- Slide 59
SELECT SYSDATE FROM DUAL;
SELECT USER FROM DUAL;

-- Slide 60
SELECT P.CD_PROJETO, P.NM_PROJETO, P.DT_INICIO, P.DT_TERMINO
FROM T_SAK_PROJETO P;

-- Slide 61
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';

SELECT P.CD_PROJETO, P.NM_PROJETO, P.DT_INICIO, P.DT_TERMINO
FROM T_SAK_PROJETO P;

-- Slide 63
SELECT 	SYSDATE,
		TO_CHAR(SYSDATE, 'MON') "MES ABREVIADO",
		TO_CHAR(SYSDATE, 'MONTH') "MES POR EXTENSO"
FROM DUAL;

ALTER SESSION SET NLS_LANGUAGE = 'PORTUGUESE';
ALTER SESSION SET NLS_LANGUAGE = 'AMERICAN';

SELECT 	SYSDATE,
		TO_CHAR(SYSDATE, 'MON') "MES ABREVIADO",
		TO_CHAR(SYSDATE, 'MONTH') "MES POR EXTENSO"
FROM DUAL;

-- Slide 64
SELECT * FROM USER_OBJECTS;
SELECT * FROM USER_TAB_COLUMNS;
SELECT * FROM USER_CONSTRAINTS;

